name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      with:
        test-bot: false

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Install Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.2.app
        sudo xcodebuild -license accept

    - name: Install dependencies
      run: |
        brew install openssl frei0r sdl2 automake cmake meson libtool wget libogg

    - name: Build project
      run: |
        ./build.sh -j4

    - uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-static-macos15-arm64
        path: bin/ffmpeg

